### ISSUE TITLE
gradlew bootRun is failing

### ISSUE THREAD

**Issue by PraveenTalari** [sdeleuze/spring-kotlin-fullstack#5]
./gradlew bootRun --stacktrace
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :shared
Kotlin Multiplatform Projects are an experimental feature.

> Task :frontend:browserWebpack FAILED
.\spring-kotlin-fullstack\build\js\packages\spring-kotlin-fullstack-frontend\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:browserWebpack'.
>

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':frontend:browserWebpack'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:121)

**Comment by sdeleuze** [comment]
Hum, it runs fine locally for me. Maybe NodeJS needs to be installed. Could check if you have it?

**Comment by PraveenTalari** [comment]
Thanks for the quick reply.

node -v shows v10.12.0

**Comment by sdeleuze** [comment]
Are you using Windows?

**Comment by PraveenTalari** [comment]
yes

**Comment by PraveenTalari** [comment]
will try in mac after few hours

**Comment by sdeleuze** [comment]
It is not yet supported, it will in 1.3.50, see https://youtrack.jetbrains.com/issue/KT-31985 for more details.
